/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ProductStatus = IDL.Variant({
  'hidden' : IDL.Null,
  'available' : IDL.Null,
  'soldOut' : IDL.Null,
});
export const Size = IDL.Variant({
  'L' : IDL.Null,
  'M' : IDL.Null,
  'S' : IDL.Null,
  'XL' : IDL.Null,
  'XXL' : IDL.Null,
  'XXXXXL' : IDL.Null,
  'XXXL' : IDL.Null,
  'XXXXL' : IDL.Null,
});
export const Color = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'weight' : IDL.Nat,
  'status' : ProductStatus,
  'featured' : IDL.Bool,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(Size),
  'colors' : IDL.Vec(Color),
  'price' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Address = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
});
export const ShippingOption = IDL.Record({
  'name' : IDL.Text,
  'itemPrice' : IDL.Nat,
  'basePrice' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'total' : IDL.Nat,
  'userId' : IDL.Principal,
  'printifyCost' : IDL.Opt(IDL.Nat),
  'shippingOption' : ShippingOption,
  'timestamp' : IDL.Int,
  'shippingAddress' : Address,
  'products' : IDL.Vec(Product),
});
export const AnnouncementBanner = IDL.Record({
  'enabled' : IDL.Bool,
  'message' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const HeroSection = IDL.Record({
  'tagline' : IDL.Text,
  'headline' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const NewsletterSubscriber = IDL.Record({
  'signupDate' : IDL.Int,
  'email' : IDL.Text,
});
export const ShippingRates = IDL.Record({
  'usEconomyBase' : IDL.Nat,
  'restOfWorldPerItem' : IDL.Nat,
  'usStandardPerItem' : IDL.Nat,
  'australiaPerItem' : IDL.Nat,
  'canadaPerItem' : IDL.Nat,
  'restOfWorldBase' : IDL.Nat,
  'canadaBase' : IDL.Nat,
  'australiaBase' : IDL.Nat,
  'usEconomyPerItem' : IDL.Nat,
  'usExpressPerItem' : IDL.Nat,
  'usExpressBase' : IDL.Nat,
  'usStandardBase' : IDL.Nat,
});
export const SocialLinks = IDL.Record({
  'tiktok' : IDL.Text,
  'twitch' : IDL.Text,
  'instagram' : IDL.Text,
  'kick' : IDL.Text,
  'youtube' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCategory' : IDL.Func([Category], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateShipping' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      ['query'],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Vec(Product), IDL.Nat, Address, ShippingOption],
      [IDL.Opt(Order)],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProductBulletPoints' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Text)))],
      ['query'],
    ),
  'getAnnouncementBanner' : IDL.Func(
      [],
      [IDL.Opt(AnnouncementBanner)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getHeroSection' : IDL.Func([], [IDL.Opt(HeroSection)], ['query']),
  'getNewsletterSubscribers' : IDL.Func(
      [],
      [IDL.Vec(NewsletterSubscriber)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getProductBulletPoints' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getShippingRates' : IDL.Func([], [ShippingRates], ['query']),
  'getSocialLinks' : IDL.Func([], [IDL.Opt(SocialLinks)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderCategories' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'reorderProducts' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAnnouncementBanner' : IDL.Func([AnnouncementBanner], [], []),
  'setHeroSection' : IDL.Func([HeroSection], [], []),
  'setProductBulletPoints' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'setProductFeatured' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setProductStatus' : IDL.Func([IDL.Text, ProductStatus], [], []),
  'setShippingRates' : IDL.Func([ShippingRates], [], []),
  'setSocialLinks' : IDL.Func([SocialLinks], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitContactForm' : IDL.Func([ContactForm], [], []),
  'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCategory' : IDL.Func([Category], [], []),
  'updateOrderCost' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ProductStatus = IDL.Variant({
    'hidden' : IDL.Null,
    'available' : IDL.Null,
    'soldOut' : IDL.Null,
  });
  const Size = IDL.Variant({
    'L' : IDL.Null,
    'M' : IDL.Null,
    'S' : IDL.Null,
    'XL' : IDL.Null,
    'XXL' : IDL.Null,
    'XXXXXL' : IDL.Null,
    'XXXL' : IDL.Null,
    'XXXXL' : IDL.Null,
  });
  const Color = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'weight' : IDL.Nat,
    'status' : ProductStatus,
    'featured' : IDL.Bool,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(Size),
    'colors' : IDL.Vec(Color),
    'price' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Address = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
  });
  const ShippingOption = IDL.Record({
    'name' : IDL.Text,
    'itemPrice' : IDL.Nat,
    'basePrice' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'total' : IDL.Nat,
    'userId' : IDL.Principal,
    'printifyCost' : IDL.Opt(IDL.Nat),
    'shippingOption' : ShippingOption,
    'timestamp' : IDL.Int,
    'shippingAddress' : Address,
    'products' : IDL.Vec(Product),
  });
  const AnnouncementBanner = IDL.Record({
    'enabled' : IDL.Bool,
    'message' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const HeroSection = IDL.Record({
    'tagline' : IDL.Text,
    'headline' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const NewsletterSubscriber = IDL.Record({
    'signupDate' : IDL.Int,
    'email' : IDL.Text,
  });
  const ShippingRates = IDL.Record({
    'usEconomyBase' : IDL.Nat,
    'restOfWorldPerItem' : IDL.Nat,
    'usStandardPerItem' : IDL.Nat,
    'australiaPerItem' : IDL.Nat,
    'canadaPerItem' : IDL.Nat,
    'restOfWorldBase' : IDL.Nat,
    'canadaBase' : IDL.Nat,
    'australiaBase' : IDL.Nat,
    'usEconomyPerItem' : IDL.Nat,
    'usExpressPerItem' : IDL.Nat,
    'usExpressBase' : IDL.Nat,
    'usStandardBase' : IDL.Nat,
  });
  const SocialLinks = IDL.Record({
    'tiktok' : IDL.Text,
    'twitch' : IDL.Text,
    'instagram' : IDL.Text,
    'kick' : IDL.Text,
    'youtube' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCategory' : IDL.Func([Category], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateShipping' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        ['query'],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Vec(Product), IDL.Nat, Address, ShippingOption],
        [IDL.Opt(Order)],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProductBulletPoints' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Text)))],
        ['query'],
      ),
    'getAnnouncementBanner' : IDL.Func(
        [],
        [IDL.Opt(AnnouncementBanner)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getHeroSection' : IDL.Func([], [IDL.Opt(HeroSection)], ['query']),
    'getNewsletterSubscribers' : IDL.Func(
        [],
        [IDL.Vec(NewsletterSubscriber)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getProductBulletPoints' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getShippingRates' : IDL.Func([], [ShippingRates], ['query']),
    'getSocialLinks' : IDL.Func([], [IDL.Opt(SocialLinks)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderCategories' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'reorderProducts' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAnnouncementBanner' : IDL.Func([AnnouncementBanner], [], []),
    'setHeroSection' : IDL.Func([HeroSection], [], []),
    'setProductBulletPoints' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'setProductFeatured' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setProductStatus' : IDL.Func([IDL.Text, ProductStatus], [], []),
    'setShippingRates' : IDL.Func([ShippingRates], [], []),
    'setSocialLinks' : IDL.Func([SocialLinks], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitContactForm' : IDL.Func([ContactForm], [], []),
    'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCategory' : IDL.Func([Category], [], []),
    'updateOrderCost' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };