/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'zip' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'name' : string,
  'state' : string,
}
export interface Category {
  'id' : string,
  'order' : bigint,
  'name' : string,
  'description' : string,
}
export type Color = string;
export interface ContactForm {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface HeroSection {
  'tagline' : string,
  'headline' : string,
  'image' : [] | [ExternalBlob],
}
export interface NewsletterSubscriber {
  'signupDate' : bigint,
  'email' : string,
}
export interface Order {
  'id' : string,
  'status' : string,
  'total' : bigint,
  'userId' : Principal,
  'printifyCost' : [] | [bigint],
  'shippingOption' : ShippingOption,
  'timestamp' : bigint,
  'shippingAddress' : Address,
  'products' : Array<Product>,
}
export interface Product {
  'id' : string,
  'categoryId' : string,
  'weight' : bigint,
  'order' : bigint,
  'name' : string,
  'description' : string,
  'sizes' : Array<Size>,
  'colors' : Array<Color>,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface ShippingOption {
  'name' : string,
  'itemPrice' : bigint,
  'basePrice' : bigint,
}
export interface ShippingRates {
  'australia' : bigint,
  'usExpress' : bigint,
  'usOvernight' : bigint,
  'usStandard' : bigint,
  'canada' : bigint,
  'restOfWorld' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type Size = { 'L' : null } |
  { 'M' : null } |
  { 'S' : null } |
  { 'XL' : null } |
  { 'XXL' : null } |
  { 'XXXXXL' : null } |
  { 'XXXL' : null } |
  { 'XXXXL' : null };
export interface SocialLinks {
  'tiktok' : string,
  'twitch' : string,
  'instagram' : string,
  'kick' : string,
  'youtube' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[Category], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateShipping' : ActorMethod<[string, Array<Product>], bigint>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<
    [Array<Product>, bigint, Address, ShippingOption],
    [] | [Order]
  >,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getHeroSection' : ActorMethod<[], [] | [HeroSection]>,
  'getNewsletterSubscribers' : ActorMethod<[], Array<NewsletterSubscriber>>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getShippingRates' : ActorMethod<[], ShippingRates>,
  'getSocialLinks' : ActorMethod<[], [] | [SocialLinks]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'reorderCategories' : ActorMethod<[Array<string>], undefined>,
  'reorderProducts' : ActorMethod<[Array<string>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setHeroSection' : ActorMethod<[HeroSection], undefined>,
  'setShippingRates' : ActorMethod<[ShippingRates], undefined>,
  'setSocialLinks' : ActorMethod<[SocialLinks], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitContactForm' : ActorMethod<[ContactForm], undefined>,
  'subscribeToNewsletter' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCategory' : ActorMethod<[Category], undefined>,
  'updateOrderCost' : ActorMethod<[string, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[string, string], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];